### ISSUE TITLE
Entitlement

### ISSUE THREAD

**Issue by JeremyKPark** [oculus-samples/Unity-Decommissioned#1]
Great work, this looks like one of the best samples yet. Unfortunately, although everything is setup as described in the configuration docs here, I've not been able to get past a red 'you are not entitled to use this app'. Tried many routes.

**Comment by AlexThiv** [comment]
Hi @JeremyKPark,

We are currently investigating this issue. The current workaround for this is to push an APK to one of the channels (like  ALPHA).

**Comment by AlexThiv** [comment]
Could you try updating your headset to the latest OS and let us know if that resolved your issue.
