### ISSUE TITLE
Hung on 'Unable to detect user avatar'

### ISSUE THREAD

**Issue by metaouter** [oculus-samples/Unity-Decommissioned#3]
When I run this sample, it always hung on 'Unable to detect user avatar' until I quit from application. What problem it may be?

**Comment by jasonmeisel** [comment]
Could you provide logs to help us diagnose this issue?

From your description, it sounds like you don't have an Avatar set up for your account. This is a case that should be handled by the game, so this is a bug. That said, you can probably work around it by creating an Avatar for your account.

**Comment by metaouter** [comment]
Maybe I found the reason that my app doesn't has the privilege to access my avatar. I will apply the privilege first, then try it again.

**Comment by jasonmeisel** [comment]
Sounds like you found the fix. I'll close the issue for now.
