### ISSUE TITLE
OVR Avatar Issue when running in Editor

### ISSUE THREAD

**Issue by AdamG012** [oculus-samples/Unity-Decommissioned#5]
Hey there, first of all great work this is an extremely helpful project. However I am facing an issue when running in the unity editor I am unable to proceed passed the "loading...." screen due to the following errors:

```
[ovrAvatar2 native] stats::url file transfer failed: http response code:403
...
NullReferenceException: Object reference not set to an instance of an object
Oculus.Avatar2.AvatarLOD.Start() (at Assets/Oculus/Avatar2/Scripts/LOD/AvatarLOD.cs168)
NullReferenceException: Object reference not set to an instance of an object
Meta.Multiplayer.Avatar.AvatarEntity.InitializeImpl() (at Packages/com.meta.multiplayer.netcode-photon/Avatar/AvatarEntity.cs:129)
```

Then this just hangs for a period of time at the loading screen then says error returning to main menu but never returns.

I am currently using Unity editor 2021.3.19f1, haven't updated any packages from the ones you have set and have set the avatar on my account. However, not sure if this will help but the project initially worked and would run in the editor. Then I uploaded to AppLab and I am not sure if this was the direct cause but it would not load after this.

Thanks

**Comment by jasonmeisel** [comment]
That's odd, it seems like the `AvatarLODManager` isn't being instantiated. That's a component on the `AvatarSDKManager` object in the `Startup` scene, so it should be instantiated when the scene loads.

Is it possible you removed the object from the scene?

**Comment by AdamG012** [comment]
Hello @jasonmeisel ,

Sorry about the nuisance will close the issue. Turns out when I imported another package to use this it had overwritten part of the objects from the scene. Thanks for all your work again, I got it working.

Regards,
Adam
